import type { Interpolation, Theme } from '../types';

const garden: Interpolation<Theme> = {
  height: '100vh',
  width: '100vw',
  padding: '16px',
  backgroundColor: '#e9e7e7',
  color: '#100f0f',
  fontFamily: 'sans-serif',
  '& button': {
    border: 'none',
    padding: '8px 16px',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    backgroundColor: '#5c7f67',
    color: '#c7ffd9',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  '& hr': {
    height: '1px',
    margin: '16px auto',
    border: 'none',
    borderBottom: '1px dashed #100f0f',
  },
  '& .Stack': {
    display: 'flex',
    gap: '16px',
  },
  '& .Badge': {
    display: 'inline-block',
    padding: '4px 12px',
    borderRadius: '16px',
    backgroundColor: '#5d5656',
    color: '#e9e7e7',
  },
  '& .CheckBoxLabel': {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    cursor: 'pointer',
  },
  'input[type="checkbox"]': {
    width: '24px',
    height: '24px',
    position: 'relative',
    appearance: 'none',
    cursor: 'pointer',
  },
  'input[type="checkbox"]:before': {
    content: '""',
    width: '100%',
    height: '100%',
    boxSizing: 'border-box',
    position: 'absolute',
    top: 0,
    left: 0,
    display: 'block',
    border: '1px solid #100f0f',
    borderRadius: '8px',
    backgroundColor: 'transparent',
  },
  'input[type="checkbox"]:checked:before': {
    content: '"✗"',
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#100f0f',
    color: '#e9e7e7',
    fontSize: '16px',
  },
};

export default garden;
